name:                silicon-gallery
version:             0.1.0.0
github:              "LastaApps/silicon-gallery"
license:             GPL-3.0-only
author:              "Petr Laštovička"
maintainer:          "krasik.peta@seznam.cz"
copyright:           "2025 Petr Laštovička"

extra-source-files:
- README.md
- LICENSE

# Metadata used when publishing your package
synopsis:            Monitor published photo albums and post link to them to Discord
category:            Web Scraping

description:         Please see the README on GitHub at <https://github.com/LastaApps/silicon-gallery#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- text
- bytestring
- time
- scalpel
- http-client

library:
  source-dirs: src

executables:
  silicon-gallery:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    # - -O0 # 7.1 7.4 7.9
    dependencies:
    - silicon-gallery

tests:
  silicon-gallery-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - silicon-gallery
    - hspec
